version: '{build}'
image: Visual Studio 2022

environment:
  SNKFILE_SECRET: #THE WARDEN OF THE NORTH
    secure: 3P4OS4SqlfLaUkiCCN8xVpE6gIE3tNvcbf3mkO58u3u3x9mDyoUa5tcedEKmLEKjmxPVQq+7gC5PqOwy/nn79UpjZdniGX3AdqRqz9edSjs=

skip_commits:
  message: /(//skip\W*ci)|(read\W*me)/

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

build_script: build.cmd ci

test_script:
  - build.cmd citest

artifacts:
  - path: __package\*.nupkg
    name: NuGet
  - path: __package\*.snupkg
    name: Symbols
  - path: __package\*.zip
    name: Zip

nuget:
  disable_publish_on_pr: true

deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: '[**CHANGE LOG**](https://github.com/BitArmory/ReCaptcha/blob/master/HISTORY.md)'
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet, Symbols
      auth_token:
          secure: 6IYVNU+ZMER/LbYbvSxl7d8w1E01gFdL5D2TOIjxuaymeVjK1y7w3IZ9EG55aAI5SvhvCtzqWrhdVzHA1YChb4UT5j1Sm+MAVmELYJ4jNEw8UmtbE6W0M4/DGLUoV1+p
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/ 
          appveyor_repo_tag: true

    - provider: NuGet
      server:
      symbol_server:
      skip_symbols: false
      api_key:
          secure: +IZk1Qa5xZOHWErWMzUMpcEpah8izHmG8vTQpZBuXFHH+99tMJ9JNDqlKdkewv4X
      artifact: NuGet, Symbols
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

on_failure:
    - ps: |
            # Enables RDP for debugging and setup some tools
            # $blockRdp = $true; choco install notepad2; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
            