// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("BitArmory.ReCaptcha for .NET")]
[assembly: AssemblyProductAttribute("BitArmory.ReCaptcha")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2015")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 1/1/2015 12:00:00 AM")]
[assembly: AssemblyTrademarkAttribute("Commercial License")]
[assembly: AssemblyDescriptionAttribute("https://github.com/bchavez/BitArmory.ReCaptcha")]
[assembly: InternalsVisibleToAttribute("BitArmory.ReCaptcha.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "BitArmory.ReCaptcha for .NET";
        internal const System.String AssemblyProduct = "BitArmory.ReCaptcha";
        internal const System.String AssemblyCompany = "Brian Chavez";
        internal const System.String AssemblyCopyright = "Brian Chavez © 2015";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 1/1/2015 12:00:00 AM";
        internal const System.String AssemblyTrademark = "Commercial License";
        internal const System.String AssemblyDescription = "https://github.com/bchavez/BitArmory.ReCaptcha";
        internal const System.String InternalsVisibleTo = "BitArmory.ReCaptcha.Tests";
    }
}
